### ISSUE TITLE
YoloHub error when running default_config

### ISSUE THREAD

**Issue by Khrystofor19** [kadirnar/TrackerHub#11]
track.py", line 27, in load_detector_model
    model = YoloHub(
TypeError: __init__() got an unexpected keyword argument 'model_type'

Is there some compatibility conflict? Are we supposed to use earlier Torchyolo version in this repository?

**Comment by Khrystofor19** [comment]
Problem is resolved with pip install torchyolo==0.2.1
maybe add it to requirements.txt ?

**Comment by kadirnar** [comment]
Hello

Thank you for your interest in the repo. I am not developing this repo. Could you please use the [torchyolo](https://github.com/kadirnar/torchyolo) library?

**Comment by Khrystofor19** [comment]
Sure, I'll try torchyolo repository, thank you!
